### ISSUE TITLE
Get Travis and Gitlab tests passing

### ISSUE THREAD

**Issue by chmreid** [DataBiosphere/data-store-cli#27]
Travis and Gitlab tests are both failing due to various issues.

Get the tests into a passing state.

**Get Travis tests passing:**

- [x] fix credentials #25 
- [x] fix reference to deprecated component #26
- [x] create necessary buckets #26, DataBiosphere/data-store#65
- [x] check that necessary buckets exist #26, #40 
- [x] remove references to code that was removed from data store cli #39 
- [x] update secret store name #35 

**Get ucsc-ci.com Gitlab tests passing:**

- [x] make windows tests manual ([link](https://docs.gitlab.com/ee/ci/yaml/#whenmanual)) #34
- [x] remove references to humancellatlas.org and hca default config #41 
- [ ] fix conflicting versions in requirements.txt files #37
