### ISSUE TITLE
Remove references to HCA from codebase

### ISSUE THREAD

**Issue by chmreid** [DataBiosphere/data-store-cli#3]
Update readme to remove mentions of HCA

Update source code to remove `hca` and optionally HCA-related naming conventions

To do:
- [x] remove `hca` references in readme and replace with `dbio` references (#13)
- [x] rename folder from `hca` to `dbio` (#16)
- [x] rename command line tool from `hca` to `dbio` (#16)
- [x] replace references to config variable `HCA_CONFIG_FILE` and replace with `DBIO_CONFIG_FILE` (#16)
- [x] update configuration file location (#18)
- [ ] remove `hca` references in documentation and replace with `dbio` references (#44)

Once these are done, we can move on to Epic #51:
* add `dbio` code coverage project to codecov.io (#23)
* add `dbio` documentation to readthedocs (#49)
* add `dbio` to pip

**Comment by chmreid** [comment]
Also DCP

**Comment by chmreid** [comment]
@amarjandu had a great suggestion for renaming the CLI tool itself, which was to replace `hca` with `cgp`. This would keep the architecture of the CLI tool relatively unchanged - dss would still be a subcommand, other swagger files for other components' APIs could be added in, etc.

**Comment by chmreid** [comment]
Replace `hca` with `dbio` instead
