### ISSUE TITLE
Update third party services for new data store CLI

### ISSUE THREAD

**Issue by chmreid** [DataBiosphere/data-store-cli#51]
Need to update all of the third-party services we had linked with HumanCellAtlas/dcp-cli to work with the new data store CLI repo at DataBiosphere/data-store-cli.

- [x] add `dbio` code coverage project to codecov.io
- [x] add `dbio` documentation to readthedocs
- [x] add `dbio` project to pip

**Comment by chmreid** [comment]
Finished
