### ISSUE TITLE
Release Data Biosphere CLI tool on PyPI

### ISSUE THREAD

**Issue by chmreid** [DataBiosphere/data-store-cli#52]
Need to create a PyPI project for the Data Biosphere's data store CLI tool.

Definition of done: `pip install dbio-cli` works

Tasks:

- [x] Create a PyPI account
- [x] Create a PyPI project for Data Biosphere data store CLI tool (`dbio-cli`)
- [x] Delete all prior tags before release
- [x] Reset version to v1.0.0 before release
- [x] Update documentation with correct PyPI project name (`pip install X` and related links) (#57)
- [x] Update release tooling (Makefile, common.mk, etc.) (#56)
- [x] Update data-store requirements.txt
- [x] Update data-store-kharon requirements.txt (DataBiosphere/data-store-kharon#14)
- [x] Add @amarjandu and @natanlao as admins on the `dbio-cli` project

**Comment by chmreid** [comment]
Finished
